### ISSUE TITLE
Icons for APM Analysis

### ISSUE THREAD

**Issue by skistz** [predixdesignsystem/px-icon-set#10]
Add icons for APM analysis:
px-fea-time.svg
px-nav-compare.svg
px-nav-data-resolution.svg
px-nav-database.svg
px-nav-summary.svg
px-nav-timezone.svg
px-util-analysis.svg
px-util-asset.svg
px-util-attribute.svg
px-util-swap.svg
px-util-tag-group.svg
px-util-tag.svg

[analysis_icons.zip](https://github.com/PredixDev/px-icon-set/files/1416343/analysis_icons.zip)

**Comment by randyaskin** [comment]
Added in v2.0.18.
