### ISSUE TITLE
Px-Icons-Set not appearing in IE11/Edge

### ISSUE THREAD

**Issue by amaanr** [predixdesignsystem/px-icon-set#12]
## Expected behavior and actual behavior:
**Appears as expected on Chrome browser with all icons:**

<img width="1024" alt="screen shot 2017-11-23 at 2 14 50 pm" src="https://user-images.githubusercontent.com/110040/33346548-5d814b02-d44d-11e7-8ef3-564975748618.png">

**IE behaviour removes all px-icons:**

<img width="1024" alt="screen shot 2017-11-23 at 2 35 22 pm" src="https://user-images.githubusercontent.com/110040/33346537-51831894-d44d-11e7-87f4-b6e718919633.png">

## Environment:

App is running in an Angular 1 application hosted on a tomcat server.

Component: **px-icon-set version 2.0.13**
Browser: **Microsoft Edge and Internet Explorer 11**
OS: **Windows 10**

## Code examples

Live demo: https://3.26.203.170:8443/TaskList/
Code repo: https://github.build.ge.com/UX-Automation/WebHMI-Task-List

**Comment by katemenkhaus** [comment]
Can you give us some more detail. What have you found when debugging? 
Have you been able recreate this issue outside of your application?

**Comment by amaanr** [comment]
See screenshots below of browser consoles. IE seems to remove a lot of the HTML used to display the icons?

<img width="768" alt="screen shot 2017-11-21 at 3 08 38 pm" src="https://user-images.githubusercontent.com/110040/33680521-1a322d16-da7f-11e7-9f6f-285e73f50d7f.png">
<img width="768" alt="screen shot 2017-11-21 at 3 09 27 pm" src="https://user-images.githubusercontent.com/110040/33680522-1a5f174a-da7f-11e7-9b89-05e152940066.png">

Using the px-icons component on its own with no application displays the icons correctly but we require the icons to appear within our Angular app.

Thanks in advance.

**Comment by davidrleonard** [comment]
@amaanr If the px-icon component works in isolation, and the error only appears when you use the px-icon component in your app, the bug is likely in your app. We are unable to debug or try to fix issues that can't be recreated in isolation. I'm going to close this.
