### ISSUE TITLE
Icon Request: Extended Document Types

### ISSUE THREAD

**Issue by erikjswedberg** [predixdesignsystem/px-icon-set#14]
Our use case would benefit from having additional icons for the following file types:

Zipped files (a zipper on a page, or a page with the letters ZIP)
XML files (the letters XML on a page)
Power points (letters ppt or a pie chart on a page)
Code files as a catch all (a "</>" on a page) 

"on a page" refers to the appearance of px-doc:document, a rectangle with a folded corner.

Thank you

**Comment by skistz** [comment]
No problem - happy to put these in the design backlog. Do you have a timeline for when you need them?

**Comment by erikjswedberg** [comment]
Loose timeline, before end of February

**Comment by randyaskin** [comment]
Added in v2.1.3. Cheers.
