### ISSUE TITLE
Icon request: Resize Chart

### ISSUE THREAD

**Issue by chuckborowiczGE** [predixdesignsystem/px-icon-set#15]
# Create an Icon for Resizing Smart Signal Charts

![image](https://user-images.githubusercontent.com/31971306/36275933-508f7a36-125a-11e8-8b2e-aea5b1949593.png)

![image](https://user-images.githubusercontent.com/31971306/36275958-67b492e6-125a-11e8-89c2-284e33260e70.png)

## Use Case:
Enlarge or reduce the height of a SS chart. Charts can be made taller up to 2 times and made shorter up to 2 times from the tallest point.

## Additional Screenshots:

![image](https://user-images.githubusercontent.com/31971306/36276029-97f922c8-125a-11e8-8d04-e2b59606b00a.png)

![image](https://user-images.githubusercontent.com/31971306/36276070-b93d2dda-125a-11e8-96e9-f1f19c3861ba.png)

## Desired Doneness:
For this to be complete, the icon should be introduced into Predix by Tuesday 2/20/2018.

**Comment by chuckborowiczGE** [comment]
I've created an SVG for the new icon. Can someone review and make sure it fits in with the set? I'm still targeting Tuesday for doneness unless I'm told otherwise. Thanks.

https://ge.box.com/s/6hq3mf9o2v83w3k0xa9h9pytsm05qnfy

**Comment by randyaskin** [comment]
Added `px-vis:resize` in v2.1.6.
