### ISSUE TITLE
Table Icon

### ISSUE THREAD

**Issue by chuckborowiczGE** [predixdesignsystem/px-icon-set#16]
# Small Table Icon proposal for APM Analysis

Q2 2018 introduces data tables into APM Analysis. This updates means we'll need to differentiate icons in the Plotted Tags section of the Tag Browser. Up until now, px-doc:chart was used to identify the widget type – it was _always_ a chart.

![image](https://user-images.githubusercontent.com/31971306/37415197-38abd6d0-2781-11e8-8b8f-642453378a5d.png)

![image](https://user-images.githubusercontent.com/31971306/37415207-43c38efa-2781-11e8-8716-30d2c7474293.png)

## Proposed Table Icon

In cases where the user opts for a data table instead, Analysis would update the icon to match the widget.

![image](https://user-images.githubusercontent.com/31971306/37415346-9d2055c8-2781-11e8-83b6-c4c6ac5cca56.png)

![image](https://user-images.githubusercontent.com/31971306/37415363-a8492556-2781-11e8-9c35-6c85601f3b42.png)

## Timeline

The icon would need to be included in the Predix icon set before the end of Q2. I can provide the SVG when you're ready.

**Comment by chuckborowiczGE** [comment]
I've got a _16x16 px_ SVG ready to go, located on Box: https://ge.box.com/s/mxy1cn8g4nl98wqvltji0gcrcqp3ak7y

**Comment by randyaskin** [comment]
Added in v2.1.9.
