### ISSUE TITLE
__VCAP_ID__ cookie is not secured

### ISSUE THREAD

**Issue by kobilemberg** [predixdesignsystem/px-icon-set#17]
Hi,

My name is Kobi.
We are using px-icon-set as part of our applications that deployed in Predix.
We also using Tinfoil web scan to scan our app.
our latest scan find the following vulnerability:

URL | ..../bower_components/px-icon-set/px-icon.html
Method | GET
Variable | __VCAP_ID__
Element | cookie

according to tinfoil the fix should be:
Set the 'Secure' flag in the cookie, such that all cookies are served over a secure channel like HTTPS only

Expected behavior:
px-icon-set component response should not return insecure cookie.

Current behavior:
px-icon-set component response contains __VCAP_ID__ cookie without secure flag.

Steps to reproduce:
1. integrate px-icon-set in app x (import this component in your html)
2. upload app x to predix.io
3. browse to app x 
2. you can see this cookie as part of the response.

**Comment by davidrleonard** [comment]
px-icon-set has nothing to do with how you serve the files up in your web server. We do not set cookies. You do that in your application code.

**Comment by kobilemberg** [comment]
Hi, we also not set any cookies in the code. We think that maybe px icon set component call to other web services to import external CSS/HTML file in the client side. If our code is not adding this header so who can do it? The scanner find it in the component URL. If you are from GE we can setup a meeting to see a demo
