### ISSUE TITLE
Refresh icon getting cut around round edges when stroke width is increased.

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-icon-set#18]
Hi,

Trying to edit style on px-icon 'px-vis:refresh' by modifying its width, but the icon is getting cut around the edges.
Below image shows how it is getting cut at top and left when icreased stroke-with to 2.5px:
![image](https://user-images.githubusercontent.com/37838320/39178898-857b5638-47d0-11e8-930f-dc0b82afd0e9.png)

We even tried changing stroke-width (stroke-width: 3px) on demo page, similar error was seen.
Please let us know how to handle this.

**Comment by nonmetalhail** [comment]
There is no way to handle it; it is just a problem if you increase the stroke-width too much and each icon will be different. Each icon is optimized for its size and changing properties may work, or clipping may occur
