### ISSUE TITLE
Icon Request:  Healthcare Imaging Machine (Donut + table)

### ISSUE THREAD

**Issue by dojabr** [predixdesignsystem/px-icon-set#2]
As the leading vendor of Imaging technology (MR, CT), GE Healthcare digital experiences could greatly benefit from the addition of an Imaging Machine icon much like Aviation/Rail benefit from plane/train icons.

For examples of the real machines, check these out for reference
https://www.google.com/search?q=imaging+machine&rlz=1C1GGRV_enUS753US753&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiyqergscjVAhXDdpoKHfrXChYQ_AUICygC&biw=1366&bih=638

For examples of their iconic representation, reference these
https://www.google.com/search?rlz=1C1GGRV_enUS753US753&biw=1366&bih=638&tbm=isch&sa=1&q=imaging+machine+icons&oq=imaging+machine+icons&gs_l=psy-ab.3...161598.162531.0.162671.6.6.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..6.0.0.xQKyGpfA_FI

Thanks in advance for the consideration
Doug

**Comment by nonmetalhail** [comment]
Passing this on to our designers

**Comment by randyaskin** [comment]
Hey Doug - I've been exploring some options, what do you think? I think I'm leaning toward one of the two in the middle of the top row...

![imaging machine](https://user-images.githubusercontent.com/2130613/29133389-287860ce-7ce8-11e7-80c2-d0777ce04069.png)

**Comment by dojabr** [comment]
Wow, thanks for the lightning fast turnaround and splendid craftsmanship Randy
I too gravitate to your top middle two, although using an isometric view explored in the 2nd row might have clearer recognition.    I wonder if top #3 given an isometric view (rotated ~25 degrees off to the right) could be the best of both worlds.  This would the equivalent of rotating the bottom #3 a bunch more to the left.

Regarding the patient representation, I prefer an option w/o it since our needs focus singularly on the Asset, and the convention generally in healthcare is not to show a patient inside the machines.  You can see some of the slight rotation/isometric I mentioned above in these images from the gehc website.
[http://www3.gehealthcare.com/en/products/categories/magnetic_resonance_imaging?campaignid=us_hp_magnetic_resonance_imaging](url)

Thanks for asking for my input, and I'll be ecstatic w/ anything you create 
Doug

**Comment by randyaskin** [comment]
Nice, thanks for the industry perspective! We'll go with something simple and isometric for now (we can always update later if necessary):
![screen shot 2017-08-09 at 3 50 00 pm](https://user-images.githubusercontent.com/2130613/29147344-3d0f7f76-7d1b-11e7-82e1-65675b2b9181.png)

We have a few more to add in this batch, then I'll push out a new version of the icon set.

**Comment by dojabr** [comment]
Masterful :1st_place_medal:

**Comment by randyaskin** [comment]
Added in v2.0.7 of icon-set.
