### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by zabzal** [predixdesignsystem/px-icon-set#25]
Team,

Are you accepting pull requests?

Regards,

Zaheer

**Comment by evanjd** [comment]
We do. See our [contribution guide](https://www.predix-ui.com/#/develop/contribution).

If you have an enhancement in mind, you may want to bounce this off design system maintainers before starting work. Feel free to do so in this issue, or if you're a GE employee, pop into the `#predixdesignsystem` slack channel.

I'll close this issue but won't lock the conversation in case you have a follow up question.
