### ISSUE TITLE
px-obj:controller seems broken

### ISSUE THREAD

**Issue by shartte** [predixdesignsystem/px-icon-set#3]
In the compiled version of the icons, the controller icon has a broken piece of XML proecssing instruction in front of the actual SVG:

https://github.com/PredixDev/px-icon-set/blob/c152d734a8744d6bcab813eb7a5c88b8917bcaa4/px-icon-set-object.html#L14

Checking the source SVGs, comparing it against other icons, the controller seems to have the Illustrator generator comment at the top, while the other SVG's don't:
https://github.com/PredixDev/px-icon-set/blob/master/icons/src-obj/controller_32x32.svg?short_path=6ffc9ed

**Comment by randyaskin** [comment]
Fixed in v2.0.8.

**Comment by shartte** [comment]
Thanks!

The controller icon was just what we needed :)
