### ISSUE TITLE
QR Code and QR Code Scanner Icons

### ISSUE THREAD

**Issue by bjoberg** [predixdesignsystem/px-icon-set#4]
# Submit an Issue

## Expected behavior:
I expect there to be a QR code and a QR code scanner icon in the px-icon-set so I can use them in my application. Unfortunately, I am not able to use the px-dropdown the way I want to use it because the icon I need is unavailable.

For example:
```javascript
<px-dropdown
  items='[{"key":"1","val":"iPhone"},{"key":"2","val":"Android"},{"key":"3","val":"Blackberry"},{"key":"4","val":"Windows Phone"},{"key":"5","val":"Flip Phone","disabled":true}]'
  sort-mode="key"
  button-style="icon"
  display-value="Select"
  icon="<<ERROR: no icon available>>"
  disable-clear>
</px-dropdown>
```

## Ideas
* **qr-code**: [http://fontawesome.io/icon/qrcode/](http://fontawesome.io/icon/qrcode/)
* **qr-code-scanner**: [https://thenounproject.com/term/qr-code-scanner/59262/](https://thenounproject.com/term/qr-code-scanner/59262/)

**Comment by mdwragg** [comment]
@skistz ^^

**Comment by skistz** [comment]
@bjoberg I can look into adding one. Can you send me a screenshot of your menu?

**Comment by bjoberg** [comment]
@skistz 
![qrcodeicons](https://user-images.githubusercontent.com/8784586/32611066-96277050-c532-11e7-962f-4e339c82c311.png)

**Comment by skistz** [comment]
To clarify: looks like you're asking for two icons - one to initiate the scanner and a second to indicate an item has been scanned (Eastern Plant)? Is that accurate? Are things being scanned via a phone or a scanner tool? If via the phone, I think the camera icon works.

**Comment by bjoberg** [comment]
Yes, this is an accurate description. Our team is fine with using the camera icon to indicate the QR code scanner, but we are still looking for a QR code icon. Something similar to this (http://fontawesome.io/icon/qrcode/) would work great.

Thanks.

**Comment by skistz** [comment]
16x16 QR Code icon attached for addition in px-icon-set

[px-utl_qrcode.svg.zip](https://github.com/PredixDev/px-icon-set/files/1488958/px-utl_qrcode.svg.zip)

**Comment by bjoberg** [comment]
@skistz it looks great! Thanks for your help.

**Comment by randyaskin** [comment]
px-utl:qr-code added in v2.1.2.
