### ISSUE TITLE
Missing icon from the stencils

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/px-icon-set#5]
The icon for Ingestion that appears on the px-stencils is not part of the icon set available for development.

![screen shot 2017-09-28 at 11 45 00 am](https://user-images.githubusercontent.com/6137443/30984634-b1da8dca-a442-11e7-8b34-7d538457cd39.png)

Could you add it please?

**Comment by randyaskin** [comment]
Added in v2.0.13.
