### ISSUE TITLE
Icon request: nav:collapse, nav:expand left and right

### ISSUE THREAD

**Issue by chuckborowiczGE** [predixdesignsystem/px-icon-set#6]
## Alternative Expand/Collapse Icons

• APM Analysis uses left/right collapse/expand icons
• An alternative set of icons would work (the current set faces up/down)

### Refresh Icons
![image](https://user-images.githubusercontent.com/31971306/31084006-3c5f406e-a761-11e7-8051-2ee0101385b8.png)

### Current Context
The right sidebar move expands from and collapses to the right.
![image](https://user-images.githubusercontent.com/31971306/31084156-a74d9560-a761-11e7-8fed-35e2c3a52576.png)

**Comment by randyaskin** [comment]
We could add additional icons for this, but it's also easily achievable with CSS, e.g.
```
<px-icon icon="px-nav:expand" style="transform:rotate(-90deg)">
<px-icon icon="px-nav:collapse" style="transform:rotate(-90deg)">
```

**Comment by chuckborowiczGE** [comment]
Perfect. Feels like this is a closed issue? (Not sure if I should close or if someone else weighs in on doneness.)
