### ISSUE TITLE
Time Zone Icon

### ISSUE THREAD

**Issue by chuckborowiczGE** [predixdesignsystem/px-icon-set#7]
Analysis needs a 16px icon for timezone selection. We planned to use the font-awesome globe icon prior to Refresh.

![image](https://user-images.githubusercontent.com/31971306/31185841-054a1158-a8fb-11e7-9d9c-b59eed4376ad.png)

Development is asking for an icon in-time for Q4.

**Comment by chuckborowiczGE** [comment]
I took a crack at a new icon for timezone:

![image](https://user-images.githubusercontent.com/31971306/31241052-a77e4fae-a9d0-11e7-91f9-f968ba1f06cf.png)

16px and built in Slack, but I am not sure if it is built correctly…

**Comment by chuckborowiczGE** [comment]
I took another shot at a timezone logo, 16px. Here it is in-context:

![image](https://user-images.githubusercontent.com/31971306/31357935-aea4b306-ad11-11e7-8660-78710a9cc235.png)

![image](https://user-images.githubusercontent.com/31971306/31357958-bf85938e-ad11-11e7-9e6c-0291381cabdd.png)

**Comment by randyaskin** [comment]
px-nav:timezone added in latest.
