### ISSUE TITLE
Data Resolution Icon

### ISSUE THREAD

**Issue by chuckborowiczGE** [predixdesignsystem/px-icon-set#8]
APM Analysis needs an icon to represent Data Resolution. We had planned to use the "signal" icon from Font-Awesome prior to the Refresh. "Signal" isn't the best choice, but it made the most sense given what font-awesome provided.

![image](https://user-images.githubusercontent.com/31971306/31186098-b9d2cd72-a8fb-11e7-9738-256ea2b4428e.png)

Development is asking for this icon in-time for Q4.

**Comment by chuckborowiczGE** [comment]
I created this icon for data resolution:

![image](https://user-images.githubusercontent.com/31971306/31240973-62e5f77a-a9d0-11e7-99a5-04579f9ab067.png)

**Comment by randyaskin** [comment]
px-nav:data-resolution added in latest version.
